export const ORCHESTRATION_ENDPOINT = process.env.NEXT_PUBLIC_ORCHESTRATION_ENDPOINT;
export const RECOGNIZER_HOST = process.env.NEXT_PUBLIC_RECOGNIZER_HOST;
export const RECOGNIZER_PATH = process.env.NEXT_PUBLIC_RECOGNIZER_PATH;
export const STATIC_PATH = process.env.NEXT_PUBLIC_SELF_PATH;
export const MOUTH_SHAPES_PATH = STATIC_PATH + "mouth-shapes";
